#!/bin/sh
curl -fsSL https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/x86_64/alpine-minirootfs-3.23.4-x86_64.tar.gz -o a.tgz

mkdir -p alpinefs
tar -xvf a.tgz -C alpinefs
rm -rf a.tgz

echo "nameserver 1.1.1.1" > alpinefs/etc/resolv.conf